### ISSUE TITLE
Decide the style and composition of colours for our website

### ISSUE THREAD

**Issue by Mariusz-Borczuk** [FilipParyz/TestingDoggos#11]
I think we could prepare a colour pallet we like or the site we want to base. We could present it on a meeting or adjust it here

**Comment by Mariusz-Borczuk** [comment]
![Color Hunt Palette ffe6e6e1afd1ad88c67469b6](https://github.com/FilipParyz/TestingDoggos/assets/116025282/6ce087dc-d269-456b-8a8b-e3c615674d85)
![Color Hunt Palette 867070d5b4b4e4d0d0f5ebeb](https://github.com/FilipParyz/TestingDoggos/assets/116025282/a9bc122d-52de-4e7e-a99e-63a21cb1cd24)

**Comment by FilipParyz** [comment]
My vote goes on:
Purple of Playfulness 💜

@mmisiewiczz What's your vote? 😄

**Comment by Mariusz-Borczuk** [comment]
![Celestial Harmony purple](https://github.com/FilipParyz/TestingDoggos/assets/116025282/2f75e85a-afa9-43b5-ab59-ffb1543911be)
    --primary-100:#7E57C2;
    --primary-200:#b085f5;
    --primary-300:#ffe8ff;
    --accent-100:#B085F5;
    --accent-200:#4d2c91;
    --text-100:#FFFFFF;
    --text-200:#e0e0e0;
    --bg-100:#2E1A47;
    --bg-200:#3f2958;
    --bg-300:#594273;

**Comment by Mariusz-Borczuk** [comment]
![Doggo management](https://github.com/FilipParyz/TestingDoggos/assets/116025282/849258e4-d70b-4890-a340-9cdef862ed62)

#FFE6E6
#e6cfcf 
#E1AFD1 
#AD88C6 
#7469B6 
#514A7F 
#B6699C 
#CB9EBC 
#765C6D 
#634E71 
#eb3223 
#78FC4C
