### ISSUE TITLE
After edit animal - values didn't change after changing values second time

### ISSUE THREAD

**Issue by mmisiewiczz** [FilipParyz/TestingDoggos#39]
Steps:

1. Choose an action: click on 'edit'
2. Choose an animal: click on 'Select an animal'
3. Click on animal name value
4. Fill in all values
5. Click on 'Edit animal'

✅result: Choosen animal's values changed

7. Change again few values 
8. Click on 'Edit animal'

❌ result: Values didn't change
❔ expected: Values change when user change them second time and click 'Edit animal'

https://github.com/FilipParyz/TestingDoggos/assets/148799634/bf87d8eb-6590-4927-bd2d-08ce85ec9d7d

**Comment by Mariusz-Borczuk** [comment]
After clicking edit Animal (submit) the select animal drop down resets as it should as we don't know which one we want to edit ;) just select in that drop down Ĺadna again

**Comment by mmisiewiczz** [comment]
We will discuss ideas at the meetings

**Comment by mmisiewiczz** [comment]
After the arrangements, I've made a change - 
- when user chooses animal or food - data automatically fill in.
- when user submits edition - data is cleared
